### PR TITLE
Allow for model-specific managing models and custom guards

### PR DESCRIPTION
**Pull request by telkins**
Decided to pull the trigger after all...wouldn't be able to sleep as well.  😜

Needs some tests, but existing tests still pass.  I'll try to get some new tests for this functionality up tomorrow.

Any feedback is still welcome. 🤓

### CODE REVIEW

**Comment by telkins** [comment]
Well, I swear I wrote a whole big issue explaining the need for this PR...but I can't find it now.  I think that I wrote it, looked at the preview, and then forgot to submit it.  😜  It's been a long, long day....

Anyway, the main need for this is to allow the obvious flexibility, while still sticking with the defaults that 99% of the people that use it will want.

The specific use case for me is when using something like Filament Admin, you may want filament users to manage some models and "default" users to manage other models.  This allows each model to default to being managed by the "default" users, but any model can override the defaults to use, for example, the filament guard and user.

That's the much shorter version of what I wrote and didn't submit....  LOL!

😴

**Comment by telkins** [comment]
It looks like the default guard is changed to whatever guard is passed when calling `actingAs()`.  Outside of testing, I don't think that when a user is authenticated that the default guard changes to whatever guard was used to authenticate.  This makes some of the tests a little murky for me...

**Comment by telkins** [comment]
I've also noticed that the foreign key constraints don't appear to be enforced...at least not under my test environment.  😒

**Comment by telkins** [comment]
I believe the code works.  I've added a few tests that pass, some of the issues with the test environment have me a bit worried about being able to properly test certain scenarios or....that I've not properly understood something.

So, I'm going to leave this PR as it is for now and get back to it once I get some feedback...or more energy to pursue a full understanding of how authentication and guards work in testing vs "normal" and sqlite's FKC support.

Hope that's OK....  🤓

**Comment by pactode** [comment]
Thanks, looks good to me. 👍

**Pull request merged**
